name: pubmed-explorer
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - hvplot
  - anaconda::biopython
  - pandas
  - pytest
  - jsonschema
  - matplotlib
  - pygraphviz
  - networkx